config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  default_url_options host: "3000"

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations' 
                                  }
  resources :users
  resources :comments
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  
  resources :articles do
    member do
      put :create_comment
     # post:create_comment
    end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'

  get '/article', to: 'static_pages#articles'

  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'

  post '/signup',  to: 'users#create'

  resources :articles

  get '/article', to: 'articles#new'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    # @article = Article.find(params[:id])
    # @comment = @article.comments.new(comment_params)
    
    # if @comment.save
    #   flash[:notice] = "Successfully saved!"
    #   redirect_to 'comments/form'
    # else
    #   flash[:alert] = "Error creating a comment!"
    #   render :new
    # end
  end
  
  def destroy
    @comment = Comment.find(params[:id])

    if @comment.destroy
      # flash[:notice] = "Successfully deleted post!"
      redirect_to :back
    else
      flash[:alert] = "Error updating comment"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :article_id, :user_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.haml
.comment-details
	%p.text-left= " #{item.user.name}, #{item.created_at.strftime('%b %d, %Y')} "
	= item.message
	= link_to "Delete", comment_path(item), method: :delete

app/views/comments/_form.html.haml
= simple_form_for @comment, url:create_comment_article_path, method: :put, remote: true do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@comment.errors.count,"error")} prohibited this post from being saved:"
      %ul
        - @comment.errors.full_message.each do |msg|
          %li
            = msg
  .container.create-comment.col-sm-12{role: 'request-comment'}
    .form-group
      = f.text_area :message, id: "comment"
      = f.button :submit , class: "btn btn-sm btn-default", role: 'submit-comment'

app/views/comments/_show.html.haml
#comments.container.col-sm-11
  = render partial: 'comments/comment', collection: @article.comments, as: :item

app/views/comments/edit.html.haml
- provide(:title,'Edit Comment')
= render 'comments/form'

app/views/comments/index.html.haml
.container
  .col-xs-12.col-md-12
    %h3 Your Comment:
    .col-mid-1.left-align
      = link_to "Add Comment", new_comment_path, class:"btn btn-md btn-default"
.container
  .col-sm-10.col-sm-offset-1.col-xs-12.comment-content
    - @comments.each do |article|
      .col-xs-12
        .text-left
          %h4 =comment.message  
          %h6 =comment.created_at.strftime('%b %d, %Y')
   

app/views/comments/new.html.haml
- provide(:title, "New Comment")
= render "comments/form"