config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  default_url_options host: "3000"

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations' 
                                  }
  resources :users
  resources :comments
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  
  resources :articles do
    member do
      put :create_comment
     # post:create_comment
    end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'

  get '/article', to: 'static_pages#articles'

  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'

  post '/signup',  to: 'users#create'

  resources :articles

  get '/article', to: 'articles#new'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: User
  belongs_to :recipient, foreign_key: :recipient_id, class_name: User

  validates :sender_id, uniqueness: {scope: :recipient_id}

  scope :between, -> (sender_id, recipient_id) do
  	where(sender_id: sender_id, recipient_id: recipient_id).or(where(sender_id: recipient_id, recipient_id: sender_id))
  end

  def self.get(sender_id,recipient_id)
  	conversation = between(sender_id, recipient_id).first	
  	return conversation if conversation.present?

  	create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])
    
    add_to_conversations unless conversated?
 
    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])
    session[:conversations].delete(@conversation.id)
 
    respond_to do |format|
      format.js
    end
  end
 
  private
 
  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end
 
  def conversated?
    session[:conversations].include?(@conversation.id)
  end


end

app/views/conversations/_conversation.html.haml
%li
  .panel.panel-default{"data-conversation-id" => "#{conversation.id}"}
    .panel-heading
      = link_to conversation.opposed_user(user).email, '', class: 'toggle-window'
      = link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post
    .panel-body{:style => "display: none;"}
      .messages-list
        %ul
          = render 'conversations/conversation_content', messages: conversation.messages, user: user
      = form_for [conversation, conversation.messages.new], remote: true do |f|
        = f.hidden_field :user_id, value: user.id
        = f.text_area :body, class: "form-control"
        = f.submit "Send", class: "btn btn-success"

app/views/conversations/_conversation_content.html.haml
- messages.each do |message|
  = render message, user: user

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
 
if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}
 
conversation.find('.panel-body').show();
 
var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);