config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  default_url_options host: "3000"

  devise_for :users, controllers: { sessions: 'users/sessions', 
                                    registrations: 'users/registrations' 
                                  }
  resources :users
  resources :comments
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
  
  resources :articles do
    member do
      put :create_comment
     # post:create_comment
    end
  end

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'

  get '/article', to: 'static_pages#articles'

  get '/help', to: 'static_pages#help'

  get '/signup', to: 'users#new'

  post '/signup',  to: 'users#create'

  resources :articles

  get '/article', to: 'articles#new'  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
    by
    %a{:href => "http://www.facebook.com/elfrancisco11"} Lloyd Francisco
  %nav
    %ul
      %li= link_to "About",   "#"
      %li= link_to "Contact", "#"
      %li
        %a{:href => "http://news.railstutorial.org/"} News
      %li= link_to image_tag("bloggerheader.png", alt: "YouBlogz logo"), '#' 

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container 
      = link_to "Lloyd Francisco", root_path, id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home",   root_path
          %li= link_to "Articles", articles_path
          %li= link_to "Help",   help_path
          \#
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Profile", user_path(current_user)
                %li= link_to "Settings", '#'
                %li.divider
                %li
                  = link_to "Log out", destroy_user_session_path, method: "delete"
          - else
            %li= link_to "Log in", new_user_session_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]--> 

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', |
      'data-turbolinks-track': 'reload'                   |
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  %body
    .container
      = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message
      = yield
  = render 'layouts/footer'
  / = debug(params) if Rails.env.development?